version: "3.9"
services:
  muon:
    build: .
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - .:/code
      - logvolume01:/var/log
    environment:
      - HOMEPATH=/root
volumes:
  logvolume01: {}